"""Report generation service -- JSON and PDF output.

Aggregates damage analysis results into a structured JSON report and
optionally renders an HTML template to PDF via WeasyPrint.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.services.damage_analyzer import DamageReport, Severity

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# HTML template for PDF report
# ---------------------------------------------------------------------------

REPORT_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>InsuraScan Damage Report</title>
<style>
  @page {{ size: A4; margin: 2cm; }}
  body {{ font-family: "Helvetica Neue", Arial, sans-serif; font-size: 11pt; color: #222; line-height: 1.5; }}
  h1 {{ color: #1a365d; border-bottom: 3px solid #2b6cb0; padding-bottom: 8px; }}
  h2 {{ color: #2b6cb0; margin-top: 24px; }}
  .header {{ display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 20px; }}
  .logo {{ font-size: 24pt; font-weight: bold; color: #2b6cb0; }}
  .meta {{ text-align: right; font-size: 9pt; color: #666; }}
  .vehicle-info {{ background: #ebf4ff; border-radius: 8px; padding: 12px 16px; margin-bottom: 20px; }}
  .vehicle-info table {{ width: 100%; border-collapse: collapse; }}
  .vehicle-info td {{ padding: 4px 8px; }}
  .vehicle-info td:first-child {{ font-weight: bold; color: #2b6cb0; width: 140px; }}
  .damage-card {{ border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px 16px; margin-bottom: 12px; page-break-inside: avoid; }}
  .damage-header {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px; }}
  .damage-title {{ font-weight: bold; font-size: 12pt; }}
  .badge {{ display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 9pt; font-weight: bold; text-transform: uppercase; }}
  .badge-minor {{ background: #c6f6d5; color: #22543d; }}
  .badge-moderate {{ background: #fefcbf; color: #744210; }}
  .badge-severe {{ background: #fed7d7; color: #822727; }}
  .damage-details {{ font-size: 10pt; color: #444; }}
  .damage-details p {{ margin: 4px 0; }}
  .cost {{ font-weight: bold; color: #2b6cb0; }}
  .cost-table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
  .cost-table th, .cost-table td {{ border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }}
  .cost-table th {{ background: #2b6cb0; color: white; }}
  .cost-table tr:nth-child(even) {{ background: #f7fafc; }}
  .cost-table .total {{ font-weight: bold; background: #ebf4ff; }}
  .summary {{ background: #f7fafc; border-left: 4px solid #2b6cb0; padding: 12px 16px; margin-top: 20px; font-style: italic; }}
  .confidence {{ font-size: 9pt; color: #888; }}
  .footer {{ margin-top: 30px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 8pt; color: #999; text-align: center; }}
</style>
</head>
<body>

<div class="header">
  <div class="logo">InsuraScan</div>
  <div class="meta">
    <div>Report Generated: {generated_at}</div>
    <div>Assessment ID: {assessment_id}</div>
    <div>Claim: {claim_number}</div>
  </div>
</div>

<h1>Vehicle Damage Assessment Report</h1>

<div class="vehicle-info">
  <table>
    <tr><td>Vehicle</td><td>{vehicle_year} {vehicle_make} {vehicle_model}</td></tr>
    <tr><td>VIN</td><td>{vin}</td></tr>
    <tr><td>Claim Number</td><td>{claim_number}</td></tr>
    <tr><td>Agent</td><td>{agent_id}</td></tr>
  </table>
</div>

<h2>Damage Items ({damage_count})</h2>

{damage_cards_html}

<h2>Cost Breakdown</h2>

<table class="cost-table">
  <thead>
    <tr><th>#</th><th>Location</th><th>Type</th><th>Severity</th><th>Low Est.</th><th>High Est.</th></tr>
  </thead>
  <tbody>
    {cost_rows_html}
    <tr class="total">
      <td colspan="4">TOTAL ESTIMATE</td>
      <td>${total_low:,.0f}</td>
      <td>${total_high:,.0f}</td>
    </tr>
  </tbody>
</table>

<p><strong>Recommendation:</strong> {recommendation}</p>

{pre_existing_html}

<div class="summary">
  <h2>Summary</h2>
  <p>{narrative}</p>
</div>

<div class="footer">
  <p>Generated by InsuraScan AI Damage Assessment Platform. This report is for informational purposes and should be verified by a certified appraiser.</p>
</div>

</body>
</html>
"""


# ---------------------------------------------------------------------------
# Service
# ---------------------------------------------------------------------------


class ReportGeneratorService:
    """Generates JSON and PDF damage reports."""

    def generate_json_report(
        self,
        damage_report: DamageReport,
        assessment_id: str = "",
        claim_number: str = "",
        vehicle_year: int = 0,
        vehicle_make: str = "",
        vehicle_model: str = "",
        vin: str = "",
        agent_id: str = "",
    ) -> dict[str, Any]:
        """Build the full JSON report structure.

        Args:
            damage_report: The DamageReport from the analyzer.
            assessment_id: UUID of the assessment.
            claim_number: Insurance claim reference.
            vehicle_year/make/model: Vehicle info.
            vin: Vehicle Identification Number.
            agent_id: Agent identifier.

        Returns:
            Complete report as a dictionary ready for JSON serialization.
        """
        return {
            "assessment_id": assessment_id,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "claim_number": claim_number,
            "agent_id": agent_id,
            "vehicle": {
                "year": vehicle_year,
                "make": vehicle_make,
                "model": vehicle_model,
                "vin": vin,
            },
            "damages": [d.model_dump() for d in damage_report.damages],
            "summary": {
                "total_damage_count": damage_report.total_damage_count,
                "total_estimate_low": damage_report.total_estimate_low,
                "total_estimate_high": damage_report.total_estimate_high,
                "recommendation": damage_report.recommendation,
                "pre_existing_damage_flags": damage_report.pre_existing_damage_flags,
                "narrative": damage_report.narrative,
            },
        }

    def generate_pdf_report(
        self,
        damage_report: DamageReport,
        output_path: Path,
        assessment_id: str = "",
        claim_number: str = "",
        vehicle_year: int = 0,
        vehicle_make: str = "",
        vehicle_model: str = "",
        vin: str = "",
        agent_id: str = "",
    ) -> Path:
        """Render the damage report as a styled PDF.

        Args:
            damage_report: The DamageReport from the analyzer.
            output_path: Where to write the PDF file.
            Other args: metadata for the report header.

        Returns:
            Path to the generated PDF file.
        """
        from weasyprint import HTML

        html = self._render_html(
            damage_report=damage_report,
            assessment_id=assessment_id,
            claim_number=claim_number,
            vehicle_year=vehicle_year,
            vehicle_make=vehicle_make,
            vehicle_model=vehicle_model,
            vin=vin,
            agent_id=agent_id,
        )

        output_path.parent.mkdir(parents=True, exist_ok=True)
        HTML(string=html).write_pdf(str(output_path))
        logger.info("PDF report generated: %s", output_path)
        return output_path

    def _render_html(
        self,
        damage_report: DamageReport,
        assessment_id: str,
        claim_number: str,
        vehicle_year: int,
        vehicle_make: str,
        vehicle_model: str,
        vin: str,
        agent_id: str,
    ) -> str:
        """Render the HTML template with report data."""
        # Build damage cards HTML
        damage_cards = []
        for d in damage_report.damages:
            badge_class = f"badge-{d.severity.value}"
            card = f"""\
<div class="damage-card">
  <div class="damage-header">
    <span class="damage-title">{d.damage_id}: {d.location}</span>
    <span class="badge {badge_class}">{d.severity.value}</span>
  </div>
  <div class="damage-details">
    <p><strong>Type:</strong> {d.damage_type}</p>
    <p>{d.description}</p>
    <p><strong>Affected Parts:</strong> {", ".join(d.affected_parts) if d.affected_parts else "N/A"}</p>
    <p><strong>Repair Method:</strong> {d.repair_method}</p>
    <p class="cost">Estimated Cost: ${d.estimated_cost_low:,.0f} -- ${d.estimated_cost_high:,.0f}</p>
    <p class="confidence">Confidence: {d.confidence_score:.0%}</p>
  </div>
</div>"""
            damage_cards.append(card)

        # Build cost rows HTML
        cost_rows = []
        for d in damage_report.damages:
            badge_class = f"badge-{d.severity.value}"
            row = (
                f"<tr>"
                f"<td>{d.damage_id}</td>"
                f"<td>{d.location}</td>"
                f"<td>{d.damage_type}</td>"
                f"<td><span class='badge {badge_class}'>{d.severity.value}</span></td>"
                f"<td>${d.estimated_cost_low:,.0f}</td>"
                f"<td>${d.estimated_cost_high:,.0f}</td>"
                f"</tr>"
            )
            cost_rows.append(row)

        # Pre-existing damage flags
        pre_existing_html = ""
        if damage_report.pre_existing_damage_flags:
            flags = "".join(
                f"<li>{flag}</li>"
                for flag in damage_report.pre_existing_damage_flags
            )
            pre_existing_html = (
                f'<div style="background:#fff5f5;border-left:4px solid #c53030;'
                f'padding:12px 16px;margin-top:16px;">'
                f"<h3>Pre-Existing Damage Flags</h3>"
                f"<ul>{flags}</ul></div>"
            )

        return REPORT_HTML_TEMPLATE.format(
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            assessment_id=assessment_id or "N/A",
            claim_number=claim_number or "N/A",
            vehicle_year=vehicle_year or "Unknown",
            vehicle_make=vehicle_make or "Unknown",
            vehicle_model=vehicle_model or "Unknown",
            vin=vin or "N/A",
            agent_id=agent_id or "N/A",
            damage_count=damage_report.total_damage_count,
            damage_cards_html="\n".join(damage_cards),
            cost_rows_html="\n    ".join(cost_rows),
            total_low=damage_report.total_estimate_low,
            total_high=damage_report.total_estimate_high,
            recommendation=damage_report.recommendation or "N/A",
            pre_existing_html=pre_existing_html,
            narrative=damage_report.narrative or "No summary available.",
        )
